fix: twemoji cdn change as maxcdn down
GDGVIT/GStamps-Extension pull request #3
Opened 2023-05-11 22:13 UTC by fa993

Urgent merge required as emojis will have very poor UX. Reason behind this is because the CDN for twemoji went down.

2023-05-18 08:09 UTC, iamyajat requested changes

2023-05-18 08:09 UTC, iamyajat commented on src/popup.html
> -        <input type="file" id="sticker-file" accept="image/png" class="actual-file-input">
make the mimetype `image/*` instead of removing it all together, so that people do not try uploading files other than images

2023-05-18 17:14 UTC, iamyajat approved these changes

2023-05-18 17:14 UTC, merged

2023-06-11 12:15 UTC, fa993 commented
Closes #4